config/routes.rb
require 'api_constraints'

Oereo::Application.routes.draw do

  root to: 'spa#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'register_developer' => 'developers#new', as: 'register_developer'
  resources :developers
  resources :sessions

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :resources
      resources :users, only: [:index, :show]
      resources :licenses, only: [:index, :show]
      resources :resource_categories, only: [:index, :show]

      get '/tags/:tagged' => 'resources#index'
    end
  end

  get '/api' => 'api/api#index'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base

  # must belong to a developer
  belongs_to :developer
  validates_presence_of :developer

  before_create :generate_access_token
  validates_uniqueness_of :access_token

private
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex # TODO: unique db constraint
    end while self.class.exists?(access_token: access_token)
  end
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  # password
  has_secure_password
  validates_presence_of :password, on: :create
  validates_length_of :password, minimum: 5

  # email
  validates :email, presence: true, uniqueness: true
  validates_formatting_of :email

  # api_key
  has_one :api_key
  validates_presence_of :api_key

  before_validation :renew_access_token, on: :create
  def renew_access_token
    self.api_key.destroy if self.api_key.present?
    self.create_api_key
  end

  def access_token
    self.api_key.access_token
  end

  def to_s
    return self.email
  end
end

app/models/license.rb
class License < ActiveRecord::Base
  validates_uniqueness_of :title
  validates_formatting_of :agreement_url, using: :url
end

app/models/resource.rb
class Resource < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :user

  belongs_to :resource_category
  validates_presence_of :resource_category

  belongs_to :license

  validates :url, presence: true
  validates_formatting_of :url

  validates :title, presence: true, length: { maximum: 140 }

end

app/models/resource_category.rb
class ResourceCategory < ActiveRecord::Base
  has_many :resources
  validates :category, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base

  # username
  validates :username, presence: true, length: { minimum: 4, maximum: 20 }
  validates_uniqueness_of :username

  # password
  has_secure_password
  validates_presence_of :password, on: :create
  validates_length_of :password, minimum: 5

  # email
  validates :email, presence: true, uniqueness: true
  validates_formatting_of :email

  def to_s
    return self.email
  end

end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController

  respond_to :json, :xml

  # turn off csrf for api-calls
  skip_before_filter :verify_authenticity_token

  before_filter :authorize_token!

  # TODO: move this to individual controllers?
  before_filter :authorize_user!, except: [:index, :show]

  # provide a nicer response at the root /api/
  def index
    respond_with resources: api_resources_url,
                 tags: api_tags_url,
                 licenses: api_licenses_url,
                 resource_categories: api_resource_categories_url
  end

protected

  def authorize_token!
    token = request.headers['X-AUTH-TOKEN']
    unless ApiKey.exists?(access_token: token)
      render :text => "Invalid access token", :status => :unauthorized
    end
  end

  def authorize_user!
    begin
      authenticate_or_request_with_http_basic do |username, password|
        # TODO: should I really rely on the instance variable?
        @user = User.find_by_username(username)
        @user.authenticate(password)
      end
    rescue
      render :text => "HTTP Basic: Malformatted header.", :status => :unauthorized
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # TODO: force_ssl

  private

  def current_developer
    @current_developer ||= Developer.find(session[:developer_id]) if session[:developer_id]
  end
  helper_method :current_developer
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController

  def index
    if current_developer
      @access_token = current_developer.access_token
    end
  end

  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)
    if @developer.save
      redirect_to root_url, flash: { success: 'Successfully registered.' }
    else
      render 'new'
    end
  end

private
  def developer_params
    params.require(:developer).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    developer = Developer.find_by_email(params[:email])
    if developer && developer.authenticate(params[:password])
      session[:developer_id] = developer.id
      redirect_to root_url, flash: { success: 'Successfully logged in' }
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:developer_id] = nil
    redirect_to root_url, notice: 'Logged out'
  end
end

app/controllers/spa_controller.rb
class SpaController < ApplicationController

  layout false

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      @access_token = current_user.access_token
    end
  end
end

app/helpers/api/api_controller_helper.rb
module Api::ApiControllerHelper
end

app/helpers/api/v1/tags_helper.rb
module Api::V1::TagsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(flash_type)
    map = {
      notice: 'info',
      success: 'success',
      error: 'danger',
      alert: 'warning'
    }
    unless map[flash_type].nil?
      "alert alert-#{map[flash_type]}"
    end
  end
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spa_helper.rb
module SpaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oereo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%# accounts %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_url %>"><strong>Oereo</strong></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <%# Logged in %>
        <% if current_developer %>

          <p class="navbar-text navbar-right"><span class="glyphicon glyphicon-user"></span> Signed in as <strong><%= current_developer.email %></strong></p>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= log_out_path %>"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
          </ul>

        <%# Logged out %>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= register_developer_path %>"><span class="glyphicon glyphicon-pencil"></span> Register a developer account</a></li>
            <li><a href="<%= log_in_path %>"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">

    <%= render partial: 'shared/flashes' %>

    <%# content %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>There were errors processing your form:</h2>
    <ul>
      <% for message in object.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="<%= bootstrap_flash_class type %>"><%= message %></div>
<% end %>